name = "gens"
version = "2.1.0"

authors = ["VSebastian8"]
description = "Gleam generators and infinite lazy lists!"
licences = ["Apache-2.0"]
repository = { type = "github", user = "VSebastian8", repo = "gens" }


[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
cat = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
